adjust_temp: false
batch_size: 32
boltzmann_confs: 32
boltzmann_steps: 5
boltzmann_training: false
boltzmann_weight: false
cache: data/H2O/cache
data_dir: data/H2O/h2o/
dataset: h2o
in_edge_features: 4
in_node_features: 74
likelihood: full
limit_train_mols: 0
log_dir: ./test_run
lr: 0.0001
max_radius: 5.0
model: tensor_product
n_epochs: 250
no_batch_norm: false
no_cache: false
no_hydrogen: false
no_residual: false
ns: 32
num_conv_layers: 4
num_intermediate_conv_layers: 2
num_workers: 1
nv: 8
optimizer: adam
pos_enc_dim: 0
radius_embed_dim: 50
restart_dir: ./pretrain
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 20
seed: 0
sigma_embed_dim: 32
sigma_max: 3.14
sigma_min: 0.031400000000000004
split_path: data/{DTST}/split.npy
std_pickles: data/{DTST}/standardized_pickles
temp: 300
tp_aggregator: mean
tp_force_aggregator: mean
use_second_order_repr: true
